services:
  vpn-browser:
    image: quay.io/mylastres0rt05_redhat/fast_vpn_container:latest
    ports:
      - "6080:6080"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    deploy:
      replicas: 2
